In [1]:
import numpy as np

<p style="font-size:2em;color:red">
Statistical Methods, Sorting and Set Operations</p>

<p style="font-size:1.7em;color:green">
Basic Stastical methods</p>

In [2]:
# setup a random 2x4 matrix
arr=10*np.random.randn(2,5)
print(arr)

[[  2.86838644   2.78321045  12.81865828   3.4004575    3.85741937]
 [ 12.60093948 -10.03312781  25.39471768  -0.17348306  -7.68952425]]


In [3]:
#compute the mean for all elements
print(arr.mean())

4.582765409899958


In [4]:
# compute the mean by row
print(arr.mean(axis=1))

[5.14562641 4.01990441]


In [5]:
# compute the mean by column 
print (arr.mean(axis=0))

[ 7.73466296 -3.62495868 19.10668798  1.61348722 -1.91605244]


In [6]:
#sum all the elements
print(arr.sum())

45.827654098999574


In [7]:
# sum elements by row
print(arr.sum(axis=1))

[25.72813206 20.09952204]


In [12]:
# compute the median
print(np.median(arr))
print()
# median by row
print(np.median(arr,axis=1))

3.1344219737644754

[ 3.4004575  -0.17348306]


<p style="font-size:1.7em;color:orange">
Sorting</p>

In [13]:
# create array of 10 random element
unsorted=np.random.randn(10)
print(unsorted)

[-0.91266897  1.20904106  0.81494139 -0.72046417 -0.69488379  0.85178475
  0.62415685 -1.01866198 -1.26826081 -1.35113731]


In [18]:
#  create copy and sort
sorted=np.array(unsorted)
sorted.sort()
print(sorted)
print()
new_sorted=sorted.sort()
print(unsorted)

[-1.35113731 -1.26826081 -1.01866198 -0.91266897 -0.72046417 -0.69488379
  0.62415685  0.81494139  0.85178475  1.20904106]

[-0.91266897  1.20904106  0.81494139 -0.72046417 -0.69488379  0.85178475
  0.62415685 -1.01866198 -1.26826081 -1.35113731]


<p style="font-size:1.7em;color:green">
Finding Unique elements</p>

In [21]:
array=np.array([1,2,1,4,2,1,4,2])
print(np.unique(array))

[1 2 4]


<p style="font-size:1.7em;color:green">
    Set Operations with<b> <u>np.array </u> </b>data type</p>

In [22]:
s1=np.array(['desk','chair','bulb'])
s2=np.array(['lamp','bulb','chair'])
print(s1,s2)

['desk' 'chair' 'bulb'] ['lamp' 'bulb' 'chair']


In [23]:
print(np.intersect1d(s1,s2))

['bulb' 'chair']


In [24]:
print(np.union1d(s1,s2))

['bulb' 'chair' 'desk' 'lamp']


In [25]:
print(np.setdiff1d(s1,s2))

['desk']


In [28]:
print(np.setdiff1d(s2,s1))

['lamp']


In [29]:
# which element of s1 is also in s2
print(np.in1d(s1,s2))

[False  True  True]
