In [1]:
import numpy as np

<p style="font-size:1.7em;color:green">
Broadcasting</p>

In [4]:
zeros_arr=np.zeros((4,3))
print(zeros_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
#create a rank 1 array with 3 values
add_rows=np.array([1,0,2])
print(add_rows)

[1 0 2]


In [6]:
y=zeros_arr+add_rows
print(y)

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


In [7]:
# create an ndarray which is 4x1 to broadcast across columns

add_cols=np.array([[0,1,2,3]])
add_cols=add_cols.T
print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [8]:
y=zeros_arr+add_cols
print(y)

[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [9]:
#this will broadcast in both dimesions
add_scalar=np.array([1])
print(zeros_arr+add_scalar)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
